spring:
  application:
    name: customer-ms
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    consumer:
      group-id: customer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    payment-result: payment-result-topic

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}
